name: Pre-Release Version Bump
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for accurate version bump
        
      - name: Get latest release tag
        id: latest-tag
        run: |
          LATEST_TAG=$(git tag -l "v[0-9]*.[0-9]*.[0-9]*" | grep -v "pre" | sort -V | tail -n 1)

          # Fallback to v0.0.0 if no release tags foundAdd commentMore actions
          if [ -z "$LATEST_TAG" ]; then
            LATEST_TAG="v0.0.0"
          fi
          echo "latest-tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Generate pre-release version
        id: pre-version
        run: |
          LATEST_TAG="${{ steps.latest-tag.outputs.latest-tag}}"
          VERSION=${LATEST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          # Increment patch for next pre-release
          PATCH=$((PATCH + 1))

          # Generate timestamp based pre-release
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          PRE_VERSION="v$MAJOR.$MINOR.$PATCH-pre-$TIMESTAMP"

          echo "pre_version=$PRE_VERSION" >> $GITHUB_OUTPUT
      
      - name: Create pre-release tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{steps.pre-version.outputs.pre_version}}
          git push origin ${{steps.pre-version.outputs.pre_version}}
